:pygments-style: tango
:source-highlighter: pygments
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 6
:numbered:
:chapter-label:
:icons: font
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images/


=== What are the disadvantages of running rootless containers ?

SEE https://github.com/containers/podman/blob/master/rootless.md

Some subcommands will not work, esp ones that depend on features like cgroups:

[source,bash]
----
[student@workstation ~]$ podman pause 382
Error: pause is not supported for rootless containers

[student@workstation ~]$ podman stats 382
Error: stats is not supported in rootless mode without cgroups v2
----

Also, networking is handled differently for rootless as a non-root user has limitations on what it can do to the host’s network:

[source,bash]
----
[student@workstation ~]$ podman run -d -p 808:8080 --name myhttpd registry.access.redhat.com/rhscl/httpd-24-rhel7
Error: error from slirp4netns while setting up port redirection: map[desc:bad request: add_hostfwd: slirp_add_hostfwd failed]
----

SEE also https://opensource.com/article/19/2/how-does-rootless-podman-work


=== Understanding user namespaces

*Root* = not different from the host

*Rootless* = maps user and group IDs to appear to be running under a different ID.

[source,bash]
----
[student@workstation ~]$ id
uid=1000(student) gid=1000(student) groups=1000(student),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

[student@workstation ~]$ podman run -it rhel7
[root@5367563cc886 /]# whoami
root
[root@5367563cc886 /]# id
uid=0(root) gid=0(root) groups=0(root)
----

student has uid=1000 in the global user namespace but is root with uid=0 inside a container.

From `man 7 user_namespaces`:

[quote]
____

In  particular, a process can have a normal unprivileged user ID outside a user namespace while at the same time having a user ID of 0 inside the namespace; in other words, the process has full privileges for operations inside the user namespace,  but is unprivileged for operations outside the namespace.

   User and group ID mappings: uid_map and gid_map
When  a  user  namespace  is  created,  it  starts  out  without  a  mapping  of  user  IDs (group IDs) to the parent user namespace.  The /proc/[pid]/uid_map and /proc/[pid]/gid_map files (available since Linux 3.5) expose the mappings for user and group IDs inside  the  user namespace  for the process pid.

Each line in the uid_map file specifies a 1-to-1 mapping of a range of contiguous user IDs between two  user  namespaces. The first two numbers specify the starting user ID in each of the two user namespaces.  The third  number  specifies  the  length  of  the mapped range.
____

You can inspect this mapping file inside a container by running:

[source,bash]
----
[root@5367563cc886 ~]$ cat /proc/self/uid_map
      (start of range)  (parent ns)      (range)
         0           1000          1
         1         100000      65536
----


So, the *root* user inside this namespace maps to the user with uid=1000 in the parent namespace (ie the “student” user).

A user with uid=1 in the child namespace would have a uid of 100000 in the parent namespace and increment up from there in the respective namespaces:

[source,bash]
----
[root@c0ec71b5ed9e /]# cat /etc/passwd
[root@c0ec71b5ed9e /]# id 1
uid=1(bin) gid=1(bin) groups=1(bin)
[root@c0ec71b5ed9e /]# id 2
uid=2(daemon) gid=2(daemon) groups=2(daemon)
[root@c0ec71b5ed9e /]# id 3
uid=3(adm) gid=4(adm) groups=4(adm)
----

These users would map to 100000, 100001, and 100002 respectively.
The child uid -> parent uid mapping for the student@workstation user can thus be summarized by:

[cols="4a,4a",options=header]
|===
|uid (child)|uid (parent)
|0|1000
|1|100000
|2|100001
|3|100002
|4|100003
|n|100000+(n-1)
|===



=== What happens when a new user is created inside this container ?

Try it out with:

[source,bash]
----
[root@c0ec71b5ed9e /]# useradd foo
[root@c0ec71b5ed9e /]# id foo
uid=1000(foo) gid=1000(foo) groups=1000(foo)
----

Within this container user_namespace, the *foo* user has a uid=1000. What would be that user\’s id outside the container ?

Use our mapping algorithm: uid=n -> uid=100000+(n-1)

The foo user with uid=1000 inside the container would thus have a uid of 100000+(1000-1) or 100999.

We can inspect the ownership of the files in the home directory for the upperdir (ephemeral storage) to prove it:

[source,bash]
----
[student@workstation ~]$ podman images
REPOSITORY                        TAG         IMAGE ID      CREATED     SIZE
registry.access.redhat.com/rhel7  latest      d19b7e812477  6 days ago  218 MB

[student@workstation ~]$ podman run registry.access.redhat.com/rhel7 useradd foo

[student@workstation ~]$ podman ps -a
CONTAINER ID  IMAGE                                    COMMAND      CREATED         STATUS                        PORTS       NAMES
be70eea7d19f  registry.access.redhat.com/rhel7:latest  useradd foo  11 seconds ago  Exited (0) 10 seconds ago                 happy_herschel

[student@workstation ~]$ podman inspect be70eea7d19f | grep UpperDir
                    "UpperDir": "/home/student/.local/share/containers/storage/overlay/2571e0f1edcf4b24bf9a54003f25ff84377ef027b1b034c757eb16c73af4139f/diff",

[student@workstation ~]$ ls -ld /home/student/.local/share/containers/storage/overlay/2571e0f1edcf4b24bf9a54003f25ff84377ef027b1b034c757eb16c73af4139f/diff/home/foo
drwx------. 2 100999 100999 62 Sep 21 10:45 /home/student/.local/share/containers/storage/overlay/2571e0f1edcf4b24bf9a54003f25ff84377ef027b1b034c757eb16c73af4139f/diff/home/foo
----


=== Understanding rootless networking

*Root* = virtual ethernet device

*Rootless* = Slirp, tap device

Container networking normally uses CNI plugins to configure a bridge, but that would require root.  For rootless, podman will execute `/usr/bin/slirp4netns` which provides userspace based networking.
This command will create a tap device that is injected inside the new networking namespace of the containerized process.

[source,bash]
----
[student@workstation ~]$ podman run -d registry.access.redhat.com/rhel7:latest sleep 5500
2a7d8b364faf2c8e825eb0bbadbfab7d113486514b74f78952c0ac29d19d1a95
[student@workstation ~]$ ps -ef | grep slirp
student     3568       1  0 11:00 pts/0    00:00:00 /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp --enable-ipv6 -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/netns-629e7aae-b8f9-d99a-efd5-4fcbb37183ee tap0
----

Also, ping might not work depending on the version of `podman` being used:

[source,bash]
----
[student@workstation ~]$ podman run -it ubi8 /bin/bash
[root@840855c79201 /]# yum install iputils
[root@ff226094dfd3 /]# ping google.com
PING google.com (172.217.1.238) 56(84) bytes of data.
^C
--- google.com ping statistics ---
57 packets transmitted, 0 received, 100% packet loss, time 57365ms
----

This has been fixed per https://bugzilla.redhat.com/show_bug.cgi?id=2037807

[source,bash]
----
[student@workstation ~]$ rpm -q systemd
systemd-239-58.el8.x86_64

[student@workstation ~]$ rpm -q --changelog systemd
* Mon Feb 07 2022 systemd maintenance team <systemd-maint@redhat.com> - 239-57
- hash-funcs: introduce macro to create typesafe hash_ops (#2037807)
- hash-func: add destructors for key and value (#2037807)
- util: define free_func_t (#2037807)
- hash-funcs: make basic hash_ops typesafe (#2037807)
- test: add tests for destructors of hashmap or set (#2037807)
- man: document the new sysctl.d/ - prefix (#2037807)
- sysctl: if options are prefixed with "-" ignore write errors (#2037807)
- sysctl: fix segfault (#2037807)

[student@workstation ~]$ sysctl -a | grep ping
net.ipv4.ping_group_range = 0    2147483647

[student@workstation ~]$ podman run -it ubi8 /bin/bash
[root@34cb445d6819 /]# yum install iputils -y

[root@34cb445d6819 /]# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=255 time=4.21 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=255 time=1.70 ms

[root@34cb445d6819 /]# exit
----

Thus, `ping` inside your rootless containers will be working in the latest DO180 classroom environments.


=== Understanding rootless storage

*Root* = native overlay2 which is a kernel module
*Rootless* = native overlay2 currently though fuse-overlayfs was used in the past

From https://www.redhat.com/sysadmin/podman-rootless-overlay

[quote]
____
The fuse-overlay has been great. However, it is a user-space file system, which means it needs to do almost twice as much work as the kernel. Every read/write has to be interpreted by the fuse-overlay before being passed onto the host kernel. For heavy workloads that hammer the file system, the performance of fuse-overlay suffers. You could see the fuse-overlayfs pegging out the CPU. Bottom line, we should see better performance with native overlayfs, especially for heavy read/write containers in rootless mode. For example, podman build . performance should improve significantly. Note that when writing to volumes, the fuse-overlayfs is seldom used, so performance will not be affected
____

The change to use the native overlay driver was first introduced in RHEL8.5 https://www.redhat.com/en/blog/whats-new-red-hat-enterprise-linux-85-container-tools See “Better Performance with Native OverlayFS“

To see the mount you’ll have to look inside the mount namespace for a running container:

[source,bash]
----
[student@workstation ~]$ lsns -t mnt
        NS TYPE NPROCS   PID USER    COMMAND
4026531840 mnt       5  1967 student /usr/lib/systemd/systemd --user
4026532257 mnt       2  2078 student catatonit -P
4026532324 mnt       1  3582 student sleep 5500
----

From the `lsns` output the `sleep 5500` has PID 3582.  Check to see what driver is used on the mounts for this containerized process:

[source,bash]
----
[student@workstation ~]$ cat /proc/3582/mounts | grep overlay
overlay / overlay rw,context="system_u:object_r:container_file_t:s0:c315,c748",relatime,lowerdir=/home/student/.local/share/containers/storage/overlay/l/FXJT5GEBB4CCTSNB6VPCWLO2OE:/home/student/.local/share/containers/storage/overlay/l/CQ5X6VLN4VJJICYQTRKJMGREJY,upperdir=/home/student/.local/share/containers/storage/overlay/6005fbe3808822c8e8e02cf1e8cfd5aadd7fd2333384ca6d72acf489b3b6ede1/diff,workdir=/home/student/.local/share/containers/storage/overlay/6005fbe3808822c8e8e02cf1e8cfd5aadd7fd2333384ca6d72acf489b3b6ede1/work 0 0
----

Notice also, there is no userspace fuse-overlayfs process running like in older versions of podman:

[source,bash]
----
[student@workstation ~]$ ps -ef | grep fuse | grep -v grep
[student@workstation ~]$
----
